---
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: keep
      MONGO_INITDB_ROOT_PASSWORD: keep
