keep:
  database:
    type: local-file
    url: localhost
    name: keep

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      group:
        readiness:
          include: diskSpace
      probes:
        enabled: true
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true